### ISSUE TITLE
Cloned the repo npm run dev fails

### ISSUE THREAD

**Issue by pmesgari** [auth0-blog/vuejs2-authentication-tutorial#6]
Hi,

I cloned and did `npm install` then `npm run dev`, starting server fails with this error:
```
Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (C:\Workspace\Vuejs\auth-app\vuejs2-authentication-tutorial\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Workspace\Vuejs\auth-app\vuejs2-authentication-tutorial\build\dev-server.js:82:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! startupbattle@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the startupbattle@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the startupbattle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs startupbattle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls startupbattle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Workspace\Vuejs\auth-app\vuejs2-authentication-tutorial\npm-debug.log
```

And this is the `npm-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle startupbattle@1.0.0~predev: startupbattle@1.0.0
6 silly lifecycle startupbattle@1.0.0~predev: no script for predev, continuing
7 info lifecycle startupbattle@1.0.0~dev: startupbattle@1.0.0
8 verbose lifecycle startupbattle@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle startupbattle@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Workspace\Vuejs\auth-app\vuejs2-authentication-tutorial\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Python36\Scripts\;C:\Python36\;C:\Users\payam.mesgari\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\payam.mesgari\AppData\Roaming\npm;C:\Program Files\Java\jre1.8.0_131;C:\Program Files\Java\jdk1.8.0_131;
10 verbose lifecycle startupbattle@1.0.0~dev: CWD: C:\Workspace\Vuejs\auth-app\vuejs2-authentication-tutorial
11 silly lifecycle startupbattle@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle startupbattle@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle startupbattle@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: startupbattle@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid startupbattle@1.0.0
16 verbose cwd C:\Workspace\Vuejs\auth-app\vuejs2-authentication-tutorial
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error startupbattle@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the startupbattle@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the startupbattle package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs startupbattle
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls startupbattle
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by unicodeveloper** [comment]
Please change the port number. 8080 is already in use by another program on your laptop.
